### ISSUE TITLE
How to build on mac? and where are your build environment?

### ISSUE THREAD

**Issue by clogic29** [xperia64/timidity-ae#1]

**Comment by xperia64** [comment]
I do not own a mac so I can't help you with any specifics. You need eclipse, the android ndk,  the android sdk, and android-support-v4-preferencefragment.

You need to run ndk-build in the root folder or the jni folder of timidity-ae to build the native libraries.
Then import the project into eclipse. You need to have the android appcompat_v7 library already set up as a library project in eclipse (note that the latest one from Google has problems). You also need the android-support-v4-preferencefragment library which is available on github. Once both of those are imported into eclipse, modify timidity-ae to ensure that it reads both of them as libraries and it should build.

**Comment by clogic29** [comment]
thx.
and what uses os? linux? or windows?

**Comment by xperia64** [comment]
I compile this on Windows, although it shouldn't make a difference if everything is set up properly.

**Comment by clogic29** [comment]
thx!!!
