### ISSUE TITLE
custom tunings?

### ISSUE THREAD

**Issue by unhandyandy** [xperia64/timidity-ae#5]
Does your version support custom tunings, e.g. do you have some equivalent of the command line -Z option?

**Comment by xperia64** [comment]
I believe command line parameters can be passed via timidity.cfg
Try checking
Settings->TiMidity++ Settings->Use manual config file
and adding a line for each command line option

```
#extension opt <command line switch here>
```

Example:

```
#extension opt --ext=I2
```
